name: WhatsApp Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies with audit fix
      run: |
        npm install
        npm audit fix --force || true  # Force fix karo, aur agar fail bhi ho toh continue karo

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run WhatsApp Bot
      run: |
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
        export NODE_ENV=production
        echo "🚀 Starting WhatsApp Bot..."
        echo "📱 QR code generate hoga, ready raho scan karne ke liye"
        node index.js
