name: WhatsApp Bot Runner

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run WhatsApp Bot
      run: |
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
        export NODE_ENV=production
        echo "🚀 Starting WhatsApp Bot..."
        node index.js
