name: WhatsApp Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node --version
        npm --version

    - name: Install dependencies
      run: |
        npm install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run WhatsApp Bot
      run: |
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
        node index.js
